# Generated by Django 4.0.4 on 2022-06-28 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.IntegerField()),
                ('nome', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=11)),
                ('pontuacao', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['nome'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='listaTitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataHora', models.DateTimeField(auto_now_add=True)),
                ('tituloAtual', models.BooleanField()),
                ('fkestudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.estudante')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('dataHora', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=10000)),
                ('texto', models.CharField(max_length=10000)),
                ('dataHora', models.DateTimeField(auto_now_add=True, null=True)),
                ('qtdPontos', models.IntegerField(default=15)),
                ('fkusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.estudante')),
            ],
        ),
        migrations.CreateModel(
            name='PostagemArmazenada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=10000)),
                ('texto', models.CharField(max_length=10000)),
                ('post_date', models.DateTimeField(blank=True, null=True)),
                ('programada', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.IntegerField()),
                ('nome', models.CharField(max_length=100)),
                ('siape', models.IntegerField()),
            ],
            options={
                'ordering': ['nome'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('dataHora', models.DateTimeField()),
                ('cumprida', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Visualizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foiVisualizado', models.BooleanField(default=False)),
                ('ehPontoExtra', models.BooleanField(default=False)),
                ('qtdPontos', models.IntegerField()),
                ('fkpostagem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.postagem')),
                ('fkprogramada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.postagemarmazenada')),
            ],
        ),
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('qtdPontos', models.IntegerField()),
                ('estudante', models.ManyToManyField(through='sistema.listaTitulo', to='sistema.estudante')),
            ],
        ),
        migrations.AddField(
            model_name='postagemarmazenada',
            name='fkusuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.professor'),
        ),
        migrations.AddField(
            model_name='listatitulo',
            name='fktitulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.titulo'),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=10000)),
                ('dataHora', models.DateTimeField(auto_now_add=True)),
                ('qtdPontos', models.IntegerField()),
                ('fkEstudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.estudante')),
                ('fkpostagem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.postagem')),
                ('fkprogramada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.postagemarmazenada')),
            ],
        ),
    ]
