# Generated by Django 4.0.4 on 2022-06-15 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=10000)),
                ('dataHora', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='listaTitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataHora', models.DateTimeField(auto_now_add=True)),
                ('tituloAtual', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('dataHora', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostagemArmazenada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=10000)),
                ('post_date', models.DateTimeField(blank=True, null=True)),
                ('tag', models.CharField(choices=[('TG1', 'Normal'), ('TG2', 'Extra')], default='TG1', max_length=10)),
                ('programada', models.BooleanField()),
                ('fkusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.professor')),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('qtdPontos', models.IntegerField()),
                ('dataHora', models.DateTimeField()),
                ('cumprida', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('qtdPontos', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='estudante',
            name='pontuacao',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='postagem',
            name='dataHora',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.DeleteModel(
            name='PostagemProgramada',
        ),
        migrations.AddField(
            model_name='titulo',
            name='estudante',
            field=models.ManyToManyField(through='sistema.listaTitulo', to='sistema.estudante'),
        ),
        migrations.AddField(
            model_name='listatitulo',
            name='fkestudante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.estudante'),
        ),
        migrations.AddField(
            model_name='listatitulo',
            name='fktitulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.titulo'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='fkEstudante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.estudante'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='fkpostagem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.postagem'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='fkprogramada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.postagemarmazenada'),
        ),
    ]
