# Generated by Django 4.0.4 on 2022-06-16 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='qtdPontos',
            field=models.IntegerField(default=15),
        ),
    ]
