# Generated by Django 4.0.5 on 2022-07-25 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tarefa',
            unique_together={('tipo', 'dataHora', 'fkestudante')},
        ),
    ]
