# Generated by Django 4.0.5 on 2022-07-27 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='qtdPontos',
        ),
    ]
