# Generated by Django 4.0.5 on 2022-07-27 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_remove_comentario_qtdpontos'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='qtdPontos',
            field=models.IntegerField(default=10),
        ),
    ]
